### ISSUE TITLE
[Suggestion] Add sub-sections within existing sections

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#143] opened 2023-12-26 21:14 UTC
Basically, if I have a collapsible Section A already, I could optionally add Section A_B in it, that pretty much acts like the existing section feature, but basically can be individually collapsed under the main Section A tab. So you could have Section A_A, A_B, A_C, A_D and so on within that one main tab and they could all be individually collapsed, or you could collapse the main section.

Or, in my case, I want to have a section called Hairs. Then within that Hairs section, I want to have sub-sections for different hairstyles. Then those sub-sections work as they do currently, but you can just collapse them individually and can also collapse the main Hairs section that hides all of the sub-sections.

**Comment by Mustard2** [comment] 2023-12-28 15:00
Hi! This seems to be a duplicate of #88 ?

**Comment by Mustard2** [comment] 2023-12-28 16:48
[MustardUI.zip](https://github.com/Mustard2/MustardUI/files/13788117/MustardUI.zip)

If you want to try, let me know if it works properly :)
You just need to select the Subsection check in the section configuration, and it will become the child section of the section above in the ordered list.

**Comment by J4ke6599** [comment] 2023-12-28 20:54
I don't notice any subsection check in the UI configuration tab.

Anyway, here is pretty much what I'm looking for:
![zrzdbxdqtpm41](https://github.com/Mustard2/MustardUI/assets/154929923/193137fa-c412-4903-8867-1dc78300b83f)

**Comment by J4ke6599** [comment] 2023-12-28 20:54
I don't see the feature, anyway, here is what I have in mind:
![yay123](https://github.com/Mustard2/MustardUI/assets/154929923/835dc403-fc24-4fed-936b-b23e65274aa0)

**Comment by Mustard2** [comment] 2023-12-29 13:09
[MustardUI-version-0.31.zip](https://github.com/Mustard2/MustardUI/files/13793703/MustardUI-version-0.31.zip)

Sorry the file above was the wrong version, this should be the correct 0.31.

**Comment by J4ke6599** [comment] 2023-12-29 17:23
Yes that's what I was looking for, do you know when will you make that part of your official version?

Also, I have another problem not related to this, I'm trying to remove some deprecated properties from the UI, but it starts giving me some sort of debug error messages. Rebuilding properties also doesn't work. So I now have a bunch of unsorted properties at the top of the list I can't get rid of.

**Comment by Mustard2** [comment] 2023-12-30 13:49
@J4ke6599 Please open a new issue with the screenshot of the problem (just beware of no NSFW policy on GitHub). If you also have the blend file with no textures, please attach a link to it so I can check faster. :)

As for this version, I have to implement a couple of functions and then it will be ready to go. Did you find any issue with the subsections?

**Comment by Mustard2** [comment] 2024-01-01 23:22
I might have fixed an error here about custom properties: https://github.com/Mustard2/MustardUI/pull/144
Let me know if it fixes your issues. :)

P.S. Do NOT release models created with beta versions of MustardUI, people might get errors trying to use your model with an older version of the addon.

**Closed** 2024-02-06 20:03 UTC
Labels: duplicate, enhancement, question
