### ISSUE TITLE
Switch armature used by the UI

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#172] opened 2024-06-06 17:23 UTC
So, earlier I made a report here about some kind of bone collection issue.

Well, today I realized that somehow my figure has two instances of armature data. One that I don't actively use on my model somehow has the UI attached to it and when I add properties to the UI, it will attach them to the unused armature data group. I also noticed that the custom properties tab is very laggy on the unused armature group.

I'm guessing that few months ago when I reset my scene, I had to split the older armature my figure uses so that only some clothing related bones were left, then joined it with the new Diffeomorphic armature. The problem is that I was obvlivious that it would keep two instances of both the new fresh Diffeomorphic armature's data and the old data, even if the old one wasn't actively used, because it was attached to the UI.

And because there's two instances of armature data, the bone collections I was complaining about not changing was because I was editing the duplicates data. And also the reason why I could delete collections on the UI and the main armature is because the collections in both the data instances share the same names, but when I create new collections on the newer armature data group, they obviously don't get transferred to the old one.

So, I'm wondering if there is a way to transfer the UI data from the duplicate to the one I'm supposed to use. If I delete the duplicate armature, all the UI settings get wiped and I don't want that since there's probably a few hours worth of work put into it.

Also, I'm interested in removing the duplicate, because I'm getting bunch of weird errors currently, that disappear as soon as I delete the duplicate, I recently noticed. They don't at least visually hinder my scene, but they're probably causing some kinds of trouble somewhere.

I get maybe 5 or 6 instances of this error:
```
find_node_operation: Failed for (TRANSFORM_FINAL, '')
--------------------------------------------------------------------
Failed to add relation "Target -> Driver"
Could not find op_from: OperationKey(type: TRANSFORM, component name: '', operation code: TRANSFORM_FINAL)
```

Then who knows how many of these with different properties:
```
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4209 BKE_animsys_eval_driver: invalid driver - ["INSERTPROPERTYNAMEHERE"][0]
```
And like I said, as soon as I delete the duplicate, I get none of it. But if I delete the duplicate, I gotta start the UI all over.

**Comment by Mustard2** [comment] 2024-12-21 20:33
Sorry I missed this.
Seems a duplicate of #100, as the cause is the fact that the Armature has two users. If you have any comment on this, please write on that issue. Closing this.

**Closed by Mustard2** 2024-12-21 20:33 UTC
Labels: duplicate
