### ISSUE TITLE
Add-on can not be activated

### ISSUE THREAD

**Issue by KoreyMiracle** [Mustard2/MustardUI#126] opened 2023-11-08 09:26 UTC
When I go to enable the addon in Blender, it gives a report error:

![Report Error](https://github.com/Mustard2/MustardUI/assets/150237532/828036ea-9ffe-495c-a55f-2ea4c37e5c18)

**Comment by Mustard2** [comment] 2023-11-08 11:25
Hi!
Is this happening in Blender 4.0?
Did you ever install MustardUI before?

I would suggest to go to your user folder and remove this folder completely
C:\Users\<YOUR_USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\MustardUI
Then restart Blender and retry the installation

**Comment by KoreyMiracle** [comment] 2023-11-08 21:34
That has been happening in Blender 4.0 and I have never installed MustardUI before. I have tried the method of removing the folder, restarting Blender, and adding the folder back in. Each and every time I get that error. Also, the folder does not have the "-master" in the name.

**Comment by Mustard2** [comment] 2023-11-09 11:30
> adding the folder back in

By "adding the folder back", you mean copy pasting the folder or installing the add-on from the Blender settings?

I would also try to revert the whole settings to default then, removing the version folders in
C:\Users\<YOUR_USERNAME>\AppData\Roaming\Blender Foundation\Blender\

Unfortunately I'm not able to replicate this on my PC, the addon is activated correctly. :(

**Comment by KoreyMiracle** [comment] 2023-11-10 07:24
I meant trying to install the .zip of the MustardUI. I tried deleting and reinstalling Blender for it to not work. I've tried deleting numerous folders and then opening Blender for the folders to regenerate. Yet, still doesn't work. I think I'm going to have to unfortunately cut my losses on this. Just can't seem to get it to work. Thank you though, really do appreciate you trying to help me out and for the quick responses!

**Comment by Mustard2** [comment] 2023-11-10 18:00
Sorry for not being able to help. I'll close this at the moment, but if someone else have the same issue, just reopen this.

**Closed by Mustard2** 2023-11-10 18:00 UTC
Labels: bug, duplicate

**Comment by KoreyMiracle** [comment] 2023-11-14 17:07
> Same issue here , nothing works

I actually found a solution that worked for me in Blender 4.0. You need to run the program as administrator and then install the .zip.

**Comment by Mustard2** [comment] 2023-11-14 19:09
This is a duplicate of #130 , let's discuss there :)
