### ISSUE TITLE
Objects name in Outfit pannel doubt ! 

### ISSUE THREAD

**Issue by LucasSculpt** [Mustard2/MustardUI#192] opened 2024-12-20 14:13 UTC
Hey dear. 

I'm using the outfit tab, and i love the option that can be used for hide ou show the singly objects  but, name objects dont apear corretcly but i noticed if i type a huge name, the UI start show the name in other words Ui just show the object name if that name have a lot of letters or a huge name btw. Can i set that name in configuration mode ?  I would like use a custom name or a short name as well !
![Mustard-1](https://github.com/user-attachments/assets/ac20df47-0f12-40ba-b7ab-f98bef346dfb)
![Mustard-2](https://github.com/user-attachments/assets/3a961fe6-e472-4ac3-a822-6245d6afb1ba)

**Comment by Mustard2** [comment] 2024-12-21 20:16
Hi! This is due to the MustardUI Naming Convention being active. If you wish you can either remove it, or respect the convention to make the correct names appear.

For more details, see the documentation: https://github.com/Mustard2/MustardUI/wiki/MustardUI-Naming-Convention

I will close this as it's not a bug, but feel free to leave more comment if you have more questions, I will answer here. :)
On the contrary, if you find any bug please open a new Issue.

**Closed by Mustard2** 2024-12-21 20:16 UTC
Labels: not-a-bug
